"""Tooling for maintaining the turtle docstring catalogs."""

import argparse
from datetime import datetime, timezone
from io import BytesIO
from pathlib import Path

from babel.messages.catalog import Catalog
from babel.messages.pofile import read_po, write_po

from sources import read_sources, refresh_sources

ROOT = Path(__file__).resolve().parent.parent
PO_DIR = ROOT / "po"
POT = PO_DIR / "turtle.pot"
PROJECT = "turtle-translations"
BUGS_ADDRESS = "https://github.com/python/turtle-translations/issues"


def build_template(data=None):
    if data is None:
        data = read_sources()
    versions = list(data["versions"])
    catalog = Catalog(
        project=PROJECT,
        version=f"{versions[0]}–{versions[-1]}",
        msgid_bugs_address=BUGS_ADDRESS,
        charset="utf-8",
        header_comment=(
            "# Docstrings of the Python turtle module.\n"
            f"# Extracted from Python {versions[0]}–{versions[-1]}.\n"
            "# This file was generated via 'scripts/i18n.py extract'."
        ),
    )
    for version, info in data["versions"].items():
        for key, doc in data["groups"][info["group"]].items():
            catalog.add(doc, auto_comments=[f"turtle.{key}", f"Python {version}: turtle.{key}"])
    return catalog


def write_catalog(catalog, path, **kwargs):
    path.parent.mkdir(parents=True, exist_ok=True)
    buffer = BytesIO()
    write_po(buffer, catalog, width=None, **kwargs)
    # avoid double newline at the end of file
    path.write_bytes(buffer.getvalue().rstrip() + b"\n")


def read_catalog(path, **kwargs):
    with path.open("rb") as f:
        return read_po(f, **kwargs)


def cmd_extract(args):
    data = refresh_sources(args.cpython) if args.cpython else read_sources()
    catalog = build_template(data)
    write_catalog(catalog, POT)
    print(f"{POT.relative_to(ROOT)}: {len(catalog)} distinct docstrings "
          f"from Python {catalog.version}")


def po_files(langs=None):
    if langs:
        return [PO_DIR / f"{lang}.po" for lang in langs]
    return sorted(PO_DIR.glob("*.po"))


def cmd_init(args):
    path = PO_DIR / f"{args.lang}.po"
    template = read_catalog(POT)
    catalog = Catalog(
        locale=args.lang,
        project=PROJECT,
        version=template.version,
        msgid_bugs_address=BUGS_ADDRESS,
        charset="utf-8",
        fuzzy=False,
    )
    catalog.update(template)
    write_catalog(catalog, path)
    print(f"Created: {path.relative_to(ROOT)}")


def cmd_update(args):
    template = read_catalog(POT)
    for path in po_files(args.langs):
        catalog = read_catalog(path)
        catalog.update(template, no_fuzzy_matching=args.no_fuzzy)
        catalog.version = template.version
        catalog.revision_date = datetime.now(timezone.utc)
        write_catalog(catalog, path, ignore_obsolete=args.drop_obsolete)
        print(f"Updated: {path.relative_to(ROOT)}")


def _load_docsdict(path, docs):
    catalog = read_catalog(path)
    result = {}
    for key, original in docs.items():
        message = catalog.get(original)
        if (message is not None and message.string and not message.fuzzy
                and f"turtle.{key}" in message.auto_comments):
            result[key] = message.string
    return result


def _module_name(lang, group):
    return f"{lang}_{group.replace('.', '')}"


def _render_shim(lang, data):
    transitions = []
    previous = None
    for version, info in data["versions"].items():
        group = info["group"]
        if group != previous:
            transitions.append((tuple(map(int, version.split("."))), group))
        previous = group
    lines = ["# Generated by scripts/i18n.py. Do not edit.", "", "import sys", ""]
    for index, (version, group) in enumerate(reversed(transitions[1:])):
        keyword = "if" if index == 0 else "elif"
        lines.extend([
            f"{keyword} sys.version_info[:2] >= {version!r}:",
            f"    from turtle_translations.{_module_name(lang, group)} import docsdict as docsdict",
        ])
    fallback = f"from turtle_translations.{_module_name(lang, transitions[0][1])} import docsdict as docsdict"
    if len(transitions) > 1:
        lines.extend(["else:", f"    {fallback}"])
    else:
        lines.append(fallback)
    return "\n".join(lines) + "\n"


def _compile_catalogs(output_dir=None):
    output_dir = ROOT if output_dir is None else Path(output_dir)
    package_dir = output_dir / "turtle_translations"
    package_dir.mkdir(parents=True, exist_ok=True)
    data = read_sources()
    written = []
    for path in po_files():
        # turtle lowercases the language before importing it!
        lang = path.stem.lower()
        for group, docs in data["groups"].items():
            target = package_dir / f"{_module_name(lang, group)}.py"
            lines = [f"# Generated from {path.name} for Python {group}.", "", "docsdict = {"]
            for key, doc in sorted(_load_docsdict(path, docs).items()):
                lines.append(f"    {key!r}: {doc!r},")
            lines.append("}")
            target.write_text("\n".join(lines) + "\n", encoding="utf-8")
            written.append(target)
        shim = output_dir / f"turtle_docstringdict_{lang}.py"
        shim.write_text(_render_shim(lang, data), encoding="utf-8")
        written.append(shim)
    return written


def cmd_compile(args):
    for path in _compile_catalogs():
        print(f"Compiled: {path.relative_to(ROOT)}")


def _catalog_stats(path):
    catalog = read_catalog(path)
    translated = fuzzy = total = 0
    for message in catalog:
        if not message.id:
            continue
        total += 1
        if message.fuzzy:
            fuzzy += 1
        elif message.string:
            translated += 1
    return translated, fuzzy, total


def cmd_stats(args):
    for path in po_files():
        translated, fuzzy, total = _catalog_stats(path)
        pct = 100 * translated // total if total else 0
        print(f"{path.stem:10} {translated:4}/{total} translated "
              f"({pct}%), {fuzzy} fuzzy")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("extract", help="write the union template `po/turtle.pot`")
    p.add_argument("--cpython", type=Path,
                   help="refresh source mappings from a CPython checkout's upstream refs")
    p.set_defaults(func=cmd_extract)

    p = sub.add_parser("init", help="create a PO file for a new language")
    p.add_argument("lang", help="language code, e.g. `pl`")
    p.set_defaults(func=cmd_init)

    p = sub.add_parser("update", help="merge the template into PO files")
    p.add_argument("langs", nargs="*", help="languages to update (default: all)")
    p.add_argument("--no-fuzzy", action="store_true",
                   help="do not fuzzy-match changed docstrings")
    p.add_argument("--drop-obsolete", action="store_true",
                   help="remove entries no longer in the template")
    p.set_defaults(func=cmd_update)

    sub.add_parser("compile", help="compile PO files").set_defaults(func=cmd_compile)

    sub.add_parser("stats", help="catalog completeness").set_defaults(func=cmd_stats)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
